//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class congviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public congviec()
        {
            this.binhluans = new HashSet<binhluan>();
            this.filechiases = new HashSet<filechiase>();
            this.nhanvien_congviec = new HashSet<nhanvien_congviec>();
        }
    
        public int congviec_id { get; set; }
        public string congviec_ten { get; set; }
        public System.DateTime congviec_ngaybatdau { get; set; }
        public System.DateTime congviec_ngayketthuc { get; set; }
        public Nullable<System.DateTime> congviec_ngayhoanthanh { get; set; }
        public int phamvi_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<binhluan> binhluans { get; set; }
        public virtual phamvi phamvi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filechiase> filechiases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanvien_congviec> nhanvien_congviec { get; set; }
    }
}
